[pytest]
pythonpath = .
testpaths = tests
addopts = -ra --strict-markers --tb=short --color=yes --video retain-on-failure

# Strict Custom Markers Configuration
markers =
    api: API path tests.
    smoke: Critical core regression path tests.
    regression: Comprehensive full system checks.
    ui: Frontend visual browser verification tests.

# Live Console Streaming Logs Configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# pytest-rerunfailures
reruns = 2
reruns_delay = 1
